### ISSUE TITLE
Default language whtout language abbreviation

### ISSUE THREAD

**Issue by valeryo** [cloudfordream/Traduction-i18n-CodeIgniter-3#2]
Hi,

is possibile to set the default language without the language abbreviation in the url?

For example:

$config['language_abbr_enable'] = TRUE;
$config['language_abbr'] = "en";

Url: https://www.example.com/en

$config['language_abbr_enable'] = FALSE;
$config['language_abbr'] = "en";

Url: https://www.example.com/

Thanks

**Comment by cloudfordream** [comment]
Hi,

This project was designed to match SEO standards, it is currently not possible to remove the language abbreviation in the url.
